2

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -3,6 +3,7 @@
 if [ -e 'start.sh' ]; then
   echo "Lets do some bashing!"
   exit 0
+else 
+  echo "start.sh script not found, skipping."
+  exit 1
 fi
-echo "start.sh script not found, skipping."
-exit 1
